### ISSUE TITLE
Enable soft-delete fails

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-keyvault-cli-extension#3]
Created a new key vault
ambapat@ambapat-linux:~$ az keyvault key create --vault-name demo9311premium --name hsmkey --protection hsm

Then ran this command to enable soft-delete, got following error
ambapat@ambapat-linux:~$ az keyvault update --enable-soft-delete --name demo9311premium
The behavior of this command has been altered by the following extension: keyvault-preview
'VaultProperties' object has no attribute 'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 405, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/home/ambapat/.azure/cliextensions/keyvault-preview/azext_keyvault/custom.py", line 367, in update_keyvault
    instance.properties.properties.enable_soft_delete = enable_soft_delete
AttributeError: 'VaultProperties' object has no attribute 'properties'

ambapat@ambapat-linux:~$ az --version
azure-cli (2.0.31)

acr (2.0.23)
acs (2.0.31)
advisor (0.5.1)
appservice (0.1.31)
backup (1.1.1)
batch (3.2.0)
batchai (0.2.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.12)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.0)
container (0.1.22)
core (2.0.31)
cosmosdb (0.1.20)
dla (0.0.19)
dls (0.0.21)
eventgrid (0.1.12)
eventhubs (0.1.2)
extension (0.0.12)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.19)
iot (0.1.19)
keyvault (2.0.21)
lab (0.0.21)
monitor (0.1.5)
network (2.0.28)
nspkg (3.0.2)
profile (2.0.22)
rdbms (0.2.1)
redis (0.2.12)
reservations (0.1.2)
resource (2.0.27)
role (2.0.22)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.31)
vm (2.0.30)

Extensions:
keyvault-preview (None)

Python location '/opt/az/bin/python3'
Extensions directory '/home/ambapat/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Apr  6 2018, 15:16:25)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by schaabs** [comment]
This issue is fixed in the [0.1.2](https://github.com/Azure/azure-keyvault-cli-extension/releases/tag/keyvault-preview_0.1.2) release
