### ISSUE TITLE
Key vault update Network Rules default-action doesn't work

### ISSUE THREAD

**Issue by amitbapat** [Azure/azure-keyvault-cli-extension#4]
ambapat@ambapat-linux:~$ az keyvault update -n demo9311premium --default-action deny
The behavior of this command has been altered by the following extension: keyvault-preview
'VaultProperties' object has no attribute 'properties'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 405, in handler
    instance = custom_function(instance=instance, **custom_func_args)
  File "/home/ambapat/.azure/cliextensions/keyvault-preview/azext_keyvault/custom.py", line 373, in update_keyvault
    if instance.properties.properties.network_acls is None:
AttributeError: 'VaultProperties' object has no attribute 'properties'
ambapat@ambapat-linux:~$

**Comment by schaabs** [comment]
This issue is fixed in the [0.1.2](https://github.com/Azure/azure-keyvault-cli-extension/releases/tag/keyvault-preview_0.1.2) release
